version: "3.8"
services:
  balance-service: 
    image: localhost/repo/real-time-balance-calculation:latest
    container_name: balance-service
    environment:
      TZ: Asia/Shang_Hai
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/balance_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
    ports:
        - "8088:8080"
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    environment:
      TZ: Asia/Shang_Hai
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      TZ: Asia/Shang_Hai
      POSTGRES_DB: balance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  redis_data:
  pg_data:
