server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/balance_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 1800000 #30 minutes

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    show-details: always
